name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Generate and Deploy Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Create directory for output
      - name: Create Output Directory
        run: mkdir -p dist

      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: KarthiJaya2795
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publish to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
